### ISSUE TITLE
GitHub and Smartthings

### ISSUE THREAD

**Issue by jelockwood** [volski/Smartthing-nuki#3]
@volski 
Thank you Volski for producing a device handler for the Nuki lock. (Nuki still have not done anything themselves.)

However the way your GitHub repo is setup prevents integrating with the Smartthings IDE interface. This is because I believe you have not followed the standard folder structure needed to enable this.

Currently your code has a URL like the following.

https://github.com/volski/Smartthing-nuki/blob/master/nukiWebApiHandler.groovy

In order to integrate with the Smartthings IDE so this it could spot updates and allow installing them via the GitHub integration you need a structure and URL like this

https://github.com/volski/Smartthing-nuki/blob/master/devicetypes/smartthings/nukiWebApiHandler.src/nukiWebApiHandler.groovy

This translates to a folder structure like this

"volski" - "Smartthing-nuki" - "devicetypes/volski" - "nukiWebApiHandler.src" - "nukiWebApiHandler.groovy"

As you will see this means adding two extra folders, the first is called "devicetypes/volski" yes with a forward slash in its name, and then the folder within that is called "nukiWebApiHandler.src" and then within that you place your groovy file.

It would be much appreciated if you could adjust your repo to this structure so as to allow the Smartthings GitHub integration to work.

**Comment by volski** [comment]
hi fixed the URL according the struct you provided
hope now it will work

**Comment by jelockwood** [comment]
Ah! Still one small issue.

You have a folder called "devicetypes/smartthings/nukiWebApiHandler.src" this folder needs to be called "devicetypes/smartthings" and then inside that you need to create the next folder called "nukiWebApiHandler.src".

You also only want the groovy file in the "nukiWebAdpiHandler.src" folder, you leave the ReadMe in the top folder.

If you want to see someone else's one as an example have a look at this one - https://github.com/jhamstead/jhamstead

**Comment by volski** [comment]
followed this guide: https://docs.smartthings.com/en/latest/tools-and-ide/github-integration.html
names have to be lowercase for some reason

try it now

**Comment by jelockwood** [comment]
Yep working now

Many thanks!

**Comment by volski** [comment]
great :)
